### ISSUE TITLE
Add/Change instructions about kubelet

### ISSUE THREAD

**Issue by cocampbe** [mapr/mapr-csi#18]
It seems that allow-privileged is defaulted to true in newer kubelet versions. It would be helpful to mention this in the installation docs. I spent a while trying to figure out how to implement this only to find I didn't need to do anything.

https://github.com/kubernetes/kubernetes/pull/63442/commits/771b8500390261db18ed0d8bbd820dbc78a3540e

**Comment by rohanjayaraj** [comment]
Closing issues older than a year.
