### ISSUE TITLE
Usage of Github releases

### ISSUE THREAD

**Issue by linkvt** [mapr/mapr-csi#31]
Hi,

I would much appreciate if you could create a new Github release when a new mapr-csi version is released so that all watchers will be informed about the new version, I just happened to notice that the csi plugin 1.1.0 is available.
The releases are currently empty: https://github.com/mapr/mapr-csi/releases 

Feel free to close this issue of course as it is just a suggestion.

Thanks,
Vincent

**Comment by rohanjayaraj** [comment]
Will follow this going forward. Thanks!
