### ISSUE TITLE
privileged is removed in "csi-nodeplugin-cr" ClusterRole

### ISSUE THREAD

**Issue by verdyr** [mapr/mapr-csi#36]
I think it is still make sense to keep privileged in "csi-nodeplugin-cr" ClusterRole

  - apiGroups: ['extensions']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
    - privileged

or otherwise, it should be a disclaimer about PSP and ways how to set it  up for mapr-csi.

**Comment by rohanjayaraj** [comment]
Closing issues older than a year.
