### ISSUE TITLE
document base64 requirement for testprovisionerrestsecret.yaml

### ISSUE THREAD

**Issue by iandow** [mapr/mapr-csi#7]
Tell users to base64 encode username and password in testprovisionerrestsecret.yaml

**Comment by ssinha3** [comment]
I think documents touches on the subject - https://mapr.com/docs/61/PersistentStorage/kdf_converting_a_string.html#concept_ogr_sxc_qcb

**Comment by iandow** [comment]
Why not just say it (echo "stuff" | base64) in the README rather than cause all kinds of anxiety in people when you tell them, "WAIT! You need to read maprdocs as well. :-)"  We want the README to be a quick start.

**Comment by sarjeet2013** [comment]
Added to the examples README
