### ISSUE TITLE
create testunsecurestorageclass.yaml for dynamic provisioning in unsecure cluster

### ISSUE THREAD

**Issue by iandow** [mapr/mapr-csi#9]
Please provide a testunsecurestorageclass.yaml for dynamic provisioning in unsecure cluster, or instruct users to remove csiNodePublishSecretName and csiNodePublishSecretNamespace from testsecurestorageclass.yaml.

**Comment by sarjeet2013** [comment]
@iandow There is already `examples/testunsecurestorageclass.yaml` in the examples section.

**Comment by iandow** [comment]
oh. My bad.
